### ISSUE TITLE
Consider upgrading drivers. 

### ISSUE THREAD

**Issue by javydekoning** [cloudrig/CloudRIG#1]
Instructions for downloading here: 
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver-windows.html 

Silent install as per: 
https://nvidia.custhelp.com/app/answers/detail/a_id/2985/~/how-can-i-perform-a-silent-install-of-the-gpu-driver%3F

**Comment by NitriKx** [comment]
The AWS AMIs are really old (mid 2018) because parsec has released a new service to rent Cloud Computer directly through them (https://support.parsecgaming.com/hc/en-us/articles/115002682891-Renting-A-Gaming-PC-From-Parsec-s-Cloud-Gaming-Marketplace). 

That means that we should maintain our own AMIs as Parsec is not going to update them.

**Comment by NitriKx** [comment]
In the new CloudRIG dedicated AMIs, the drivers are going to be at the latest version (and supports more instance types / GPUs)
